-- CreateTable
CREATE TABLE "Products" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "published" BOOLEAN DEFAULT false,
    "name" TEXT NOT NULL,
    "amount" INTEGER NOT NULL DEFAULT 999,
    "price" INTEGER NOT NULL DEFAULT 9999999,
    "totalPrice" INTEGER NOT NULL DEFAULT 99999999999999,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
